### ISSUE TITLE
Improve back2source d2d pipeline for ELFs

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/scancode.io#1339] opened 2024-07-24 17:44 UTC
There seem to be too many "requires-review" as a first glance in the summary report from a d2d project for ELF.
- https://github.com/aboutcode-org/back2source-data/blob/main/data/archive.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/debug/tree/a/atomix-debugsource-44.0-4.fc40.x86_64/d2d-summary.json#L36 has only one requires review
- https://github.com/aboutcode-org/back2source-data/blob/main/data/archive.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/debug/tree/a/atomix-debugsource-44.0-4.fc40.x86_64/d2d-details.json#L3535 has many correctly mapped paths that are marked as requires-review likely incorrectly

- Also we should not include directories and `<artificial>` and `<built-in>` (and this may something we could filter out in the elf-inspector ?)
  - like in https://github.com/aboutcode-org/back2source-data/blob/main/data/archive.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/debug/tree/a/atomix-debugsource-44.0-4.fc40.x86_64/d2d-details.json#L3398
  - or in https://github.com/aboutcode-org/back2source-data/blob/main/data/archive.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/debug/tree/a/atomix-debugsource-44.0-4.fc40.x86_64/d2d-details.json#L3493

**Comment by AyanSinhaMahapatra** [comment] 2024-11-04 10:38
This is a duplicate of https://github.com/aboutcode-org/scancode.io/issues/1403

**Closed by AyanSinhaMahapatra** 2024-11-04 10:38 UTC
